class LocalData {
  static String get about =>
      '[{"title":"Application Description","details":[{"value":"This application has all sensitivity settings form popular streamers, control layouts, damage details. This application just provides to improve your play. This application credit goes to all popular streamers. In the future, we will add tricks regularly"},{"value":"PUBG trademarked names and images are only used as a reference and we do nott intend to violate or take ownership of these names and images."}]},{"title":"DISCLAIMER","details":[{"value":"This is an UNOFFICIAL application for Control Layout Guide. This application is not associated in any way with PUBG corporation. All rights reserved In accordance with https://developer.pubg.com/tos?locale=en"},{"value":"if you feel that we have violated your intellectual property rights or any other agreement, please contact us by e-mail ananth.g1992@gmail.com. we will immediately take the necessary measures."}]}]';

  static String get controlLayouts =>
      '[{"key":"Layout 1","src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/2_fingers/1.png"},{"key":"Layout 2","src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/2_fingers/2.png"},{"key":"Layout 3","src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/2_fingers/3.png"},{"key":"Layout 4","src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/2_fingers/4.png"},{"key":"Layout 5","src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/2_fingers/5.png"},{"key":"Layout 6","src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/2_fingers/6.png"},{"key":"Layout 7","src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/2_fingers/7.png"},{"key":"Layout 8","src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/2_fingers/8.png"},{"key":"Layout 9","src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/2_fingers/9.png"}]';

  static String get controlLayouts2 =>
      '[  {  "key":"Layout 1",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/3_fingers/1.png"  },  {  "key":"Layout 2",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/3_fingers/2.png"  },  {  "key":"Layout 3",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/3_fingers/3.png"  },  {  "key":"Layout 4",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/3_fingers/4.png"  },  {  "key":"Layout 5",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/3_fingers/5.png"  },  {  "key":"Layout 6",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/3_fingers/6.png"  },  {  "key":"Layout 7",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/3_fingers/7.png"  },  {  "key":"Layout 8",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/3_fingers/8.png"  },  {  "key":"Layout 9",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/3_fingers/9.png"  },  {  "key":"Layout 10",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/3_fingers/10.png"  },  {  "key":"Layout 11",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/3_fingers/11.png"  },  {  "key":"Layout 12",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/3_fingers/12.png"  }  ]';

  static String get controlLayouts3 =>
      '[  {  "key":"Layout 1",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/4_fingers/1.png"  },  {  "key":"Layout 2",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/4_fingers/2.png"  },  {  "key":"Layout 3",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/4_fingers/3.png"  },  {  "key":"Layout 4",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/4_fingers/4.png"  },  {  "key":"Layout 5",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/4_fingers/5.png"  },  {  "key":"Layout 6",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/4_fingers/6.png"  },  {  "key":"Layout 7",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/4_fingers/7.png"  },  {  "key":"Layout 8",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/4_fingers/8.png"  },  {  "key":"Layout 9",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/4_fingers/9.png"  },  {  "key":"Layout 10",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/4_fingers/10.png"  },  {  "key":"Layout 11",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/4_fingers/11.png"  },  {  "key":"Layout 12",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/4_fingers/12.png"  } ,  {  "key":"Layout 13",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/4_fingers/13.png"  },  {  "key":"Layout 14",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/4_fingers/14.png"  },  {  "key":"Layout 15",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/4_fingers/15.png"  },  {  "key":"Layout 16",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/4_fingers/16.png"  },  {  "key":"Layout 17",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/4_fingers/17.png"  },  {  "key":"Layout 18",  "src":"https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/screen_layouts/4_fingers/18.png"  } ]';

  static String get controlSettings =>
      '[ { "value": "Best control settings for PUBG Mobile: Adjust Controls", "type": "H2" }, { "value": "Head to Settings > Controls and pick the best option which works best for you.", "type": "P" }, { "value": "https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/basic_setting/pubg-mobile-customize-controls-screens.png", "type": "IMG" }, { "value": "In the Controls tab, an “Enable 3D Touch” option is likewise available, tick it! If you have been in the habit of pressing wrong buttons, enabling 3D touch option is truly helpful advice as this option is based on your finger pressure on-screen.", "type": "p" }, { "value": "https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/basic_setting/activate-enable-3d-touch.png", "type": "IMG" }, { "value": "It’s advised not to join a battle right after Controls adjustment. Visit Training to get used to the settings first!", "type": "p" }, { "value": "Best control settings for PUBG Mobile: Customize Button Size & Location", "type": "H2" }, { "value": "At the bottom of the Controls settings screen, choose “Customize” in order to play the game the way you like.", "type": "P" }, { "value": "https://raw.githubusercontent.com/AnanthGopal/niralaakam/main/pubg/basic_setting/pubg-mobile-customize-controls-large-icons-screens.png", "type": "IMG" } ]';
}
